### ISSUE TITLE
Updating an already indexed image is not reflected in Portus

### ISSUE THREAD

**Issue by boyand** [SUSE/Portus#553]
Currently if you change an already uploaded image ( with tag "latest" for example ) and push the new version, the Portus UI does not update the timestamp to the last push. This coupled with https://github.com/SUSE/Portus/issues/512 makes it very hard to figure out if an image has been updated.

**Comment by mssola** [comment]
I agree.

**Comment by JonathonReinhart** [comment]
:+1: In addition to the timestamp, there is no entry in the "Recent activities" view.

Example: I just pushed a new version as both `:0.0.5` and as `:latest`, but "Recent activities" only shows me pushing the new tag, `:0.0.5`.

**Comment by iitns** [comment]
+1

**Comment by iitns** [comment]
+1

Though the timestamp it is not updated to the last push, pushed image is updated in distribution.

**Comment by NickHu** [comment]
+1
Still happens on latest master (4b2f3bf).
I'm a little confused at what https://github.com/SUSE/Portus/blob/4b2f3bf63866cf4b6498f58a222c186001f1a44f/app/models/repository.rb#L143-L146 is supposed to do - the comment would imply that it addresses this, but I think I may be misunderstanding it - perhaps someone could clarify?

**Comment by mssola** [comment]
@NickHu so, the thing here is that digests will get updated properly. The only thing that this is not properly updated in the `updated_at` attribute (in fact, we kind of never cared about the updated_at attribute :sweat_smile:). Moreover, a new activity should be created for that.
